---------------------------------------------------
-- Copyright (c) 2021 -- Camshaft Software PTY LTD
---------------------------------------------------

-- WARNING: DO NOT EDIT THIS FILE
-- This file gets replaced every time luaExporter is run, any changes done to this file will be overwritten

function DoExport(CarCalculator, CarFile)
	UAPI.Log("DoExport: ")

	local value = {}

	local CarFiles = CExporter.ExportCarFiles(CarCalculator)
	CarFiles[string.format("%s - %s.car", CarCalculator.CarInfo.PlatformInfo.Name, CarCalculator.CarInfo.TrimInfo.Name)] = CarFile --remove this if you don't want the file exported

	local Data = {}

	local Files = {}

	for k,v in pairs(CarFiles) do
		Files[k] = v
	end

	return Files, Data
end

if CExporter == nil then
	CExporter = {}
	CExporter.__index = CExporter
end

function CExporter.ExportCarFiles(CarCalculator)
	local CarInfo = CarCalculator.CarInfo

	Files = { }

	local outputString = ""

	outputString = outputString .. "Car Name: " .. CarInfo.PlatformInfo.Name .."\n"
	outputString = outputString .. "Trim Name: " .. CarInfo.TrimInfo.Name .."\n"
	outputString = outputString .. "Family Name: " .. CarInfo.TrimInfo.EngineInfo.PlatformInfo.Name .."\n"
	outputString = outputString .. "Family Name: " .. CarInfo.TrimInfo.EngineInfo.ModelInfo.Name .."\n"

	outputString = outputString .. "Trim Price: " .. CarInfo.TrimInfo.Results.Price .."\n"

	outputString = outputString .. "Game Version: " .. UAPI.GetGameVersion()

	Files["trimDataExport.txt"] = outputString

	return Files
end